import React from 'react';
// import styles from './index.module.css';
// import { signIn, signOut, useSession } from 'next-auth/react';
import { type NextPage } from 'next';
import Head from 'next/head';
// import { api } from '@/utils/api';
import SplashSpeedDial from '@/components/SplashSpeedDial/SplashSpeedDial';

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full min-h-screen flex-column justify-content-center align-items-center p-8 text-center ">
        <div className="flex flex-column justify-content-center align-items-center flex-wrap gap-5">
          <div>
            <h1>
              Dyslexia <br /> Dashboard
            </h1>
            <p>version 0.1.0</p>
          </div>
          <div>
            <SplashSpeedDial />
          </div>
          {/* <div className={styles.showcaseContainer}>
            <p className={styles.showcaseText}>
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div> */}
        </div>
      </main>
    </>
  );
};

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className={styles.authContainer}>
//       <p className={styles.showcaseText}>
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className={styles.loginButton}
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }

export default Home;
